 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('contact', array('action'=>'add'));?>">Add new contact</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Email</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($contacts as $contact) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($contact->name);?></td>
     <td><?php echo $this->escapeHtml($contact->email);?></td>
     <td>
         <a href="<?php echo $this->url('contact',
             array('action'=>'edit', 'id' => $contact->id));?>">Edit</a>
         <a href="<?php echo $this->url('contact',
             array('action'=>'delete', 'id' => $contact->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>